# Production profile

spring:
  servlet:
    context-path: /pospdv
  jpa:
    show-sql: false
  web:
    error:
      include-message: never
      include-binding-errors: never
      include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
